[package]
name = "rsa-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.4.3"
dioxus-desktop = "0.4.3"
num = "0.4.1"
rand = "0.8.5"
simple-message-box = "0.0.2"
